data = [
    {
        "name": "Virat Kohli",
        "follower_count": 260.73,
        "description": "Cricketer",
        "birthplace": "Delhi",
    },
    {
        "name": "Rohit Sharma",
        "follower_count": 40.18,
        "description": "Cricketer",
        "birthplace": "Nagpur, Maharashtra",
    },
    {
        "name": "MS Dhoni",
        "follower_count": 48.64,
        "description": "Former cricketer",
        "birthplace": "Ranchi, Jharkhand",
    },
    {
        "name": "Sachin Tendulkar",
        "follower_count": 40.92,
        "description": "Former cricketer",
        "birthplace": "Mumbai, Maharashtra",
    },
    {
        "name": "Hardik Pandya",
        "follower_count": 35.47,
        "description": "Cricketer",
        "birthplace": "Surat, Gujarat",
    },
    {
        "name": "KL Rahul",
        "follower_count": 30.83,
        "description": "Cricketer",
        "birthplace": "Bengaluru, Karnataka",
    },
    {
        "name": "Shubman Gill",
        "follower_count": 15.26,
        "description": "Cricketer",
        "birthplace": "Fazilka, Punjab",
    },
    {
        "name": "Jasprit Bumrah",
        "follower_count": 14.71,
        "description": "Cricketer",
        "birthplace": "Ahmedabad, Gujarat",
    },
    {
        "name": "Rishabh Pant",
        "follower_count": 16.58,
        "description": "Cricketer",
        "birthplace": "Roorkee, Uttarakhand",
    },
    {
        "name": "Ravindra Jadeja",
        "follower_count": 9.34,
        "description": "Cricketer",
        "birthplace": "Navagam Ghed, Gujarat",
    },
    {
        "name": "Suryakumar Yadav",
        "follower_count": 12.67,
        "description": "Cricketer",
        "birthplace": "Mumbai, Maharashtra",
    },
    {
        "name": "Yuvraj Singh",
        "follower_count": 20.41,
        "description": "Former cricketer",
        "birthplace": "Chandigarh",
    },
    {
        "name": "Neeraj Chopra",
        "follower_count": 9.89,
        "description": "Olympic javelin thrower",
        "birthplace": "Panipat, Haryana",
    },
    {
        "name": "Shah Rukh Khan",
        "follower_count": 45.12,
        "description": "Actor",
        "birthplace": "New Delhi",
    },
    {
        "name": "Salman Khan",
        "follower_count": 66.38,
        "description": "Actor",
        "birthplace": "Indore, Madhya Pradesh",
    },
    {
        "name": "Aamir Khan",
        "follower_count": 30.09,
        "description": "Actor",
        "birthplace": "Mumbai, Maharashtra",
    },
    {
        "name": "Amitabh Bachchan",
        "follower_count": 35.88,
        "description": "Actor",
        "birthplace": "Allahabad, Uttar Pradesh",
    },
    {
        "name": "Akshay Kumar",
        "follower_count": 67.54,
        "description": "Actor",
        "birthplace": "Amritsar, Punjab",
    },
    {
        "name": "Hrithik Roshan",
        "follower_count": 40.55,
        "description": "Actor",
        "birthplace": "Mumbai, Maharashtra",
    },
    {
        "name": "Ranveer Singh",
        "follower_count": 45.76,
        "description": "Actor",
        "birthplace": "Mumbai, Maharashtra",
    },
    {
        "name": "Ranbir Kapoor",
        "follower_count": 45.33,
        "description": "Actor",
        "birthplace": "Mumbai, Maharashtra",
    },
    {
        "name": "Ajay Devgn",
        "follower_count": 30.61,
        "description": "Actor",
        "birthplace": "New Delhi",
    },
    {
        "name": "Kartik Aaryan",
        "follower_count": 38.29,
        "description": "Actor",
        "birthplace": "Gwalior, Madhya Pradesh",
    },
    {
        "name": "Allu Arjun",
        "follower_count": 25.94,
        "description": "Actor",
        "birthplace": "Chennai, Tamil Nadu",
    },
    {
        "name": "Prabhas",
        "follower_count": 12.14,
        "description": "Actor",
        "birthplace": "Chennai, Tamil Nadu",
    },
    {
        "name": "Yash",
        "follower_count": 14.02,
        "description": "Actor",
        "birthplace": "Bengaluru, Karnataka",
    },
    {
        "name": "Vijay Deverakonda",
        "follower_count": 20.73,
        "description": "Actor",
        "birthplace": "Hyderabad, Telangana",
    },
    {
        "name": "Ram Charan",
        "follower_count": 16.91,
        "description": "Actor",
        "birthplace": "Chennai, Tamil Nadu",
    },
    {
        "name": "Jr NTR",
        "follower_count": 9.11,
        "description": "Actor",
        "birthplace": "Hyderabad, Telangana",
    },
    {
        "name": "Deepika Padukone",
        "follower_count": 80.46,
        "description": "Actress",
        "birthplace": "Copenhagen, Denmark",
    },
    {
        "name": "Priyanka Chopra Jonas",
        "follower_count": 90.67,
        "description": "Actress and producer",
        "birthplace": "Jamshedpur, Jharkhand",
    },
    {
        "name": "Alia Bhatt",
        "follower_count": 85.32,
        "description": "Actress",
        "birthplace": "Mumbai, Maharashtra",
    },
    {
        "name": "Katrina Kaif",
        "follower_count": 75.81,
        "description": "Actress",
        "birthplace": "Hong Kong",
    },
    {
        "name": "Anushka Sharma",
        "follower_count": 65.19,
        "description": "Actress",
        "birthplace": "Ayodhya, Uttar Pradesh",
    },
    {
        "name": "Kareena Kapoor Khan",
        "follower_count": 85.74,
        "description": "Actress",
        "birthplace": "Mumbai, Maharashtra",
    },
    {
        "name": "Shraddha Kapoor",
        "follower_count": 90.12,
        "description": "Actress",
        "birthplace": "Mumbai, Maharashtra",
    },
    {
        "name": "Kiara Advani",
        "follower_count": 35.03,
        "description": "Actress",
        "birthplace": "Mumbai, Maharashtra",
    },
    {
        "name": "Samantha Ruth Prabhu",
        "follower_count": 35.66,
        "description": "Actress",
        "birthplace": "Chennai, Tamil Nadu",
    },
    {
        "name": "Rashmika Mandanna",
        "follower_count": 40.08,
        "description": "Actress",
        "birthplace": "Virajpet, Karnataka",
    },
    {
        "name": "Arijit Singh",
        "follower_count": 18.57,
        "description": "Singer",
        "birthplace": "Jiaganj, West Bengal",
    },
    {
        "name": "Neha Kakkar",
        "follower_count": 80.91,
        "description": "Singer",
        "birthplace": "Rishikesh, Uttarakhand",
    },
    {
        "name": "Badshah",
        "follower_count": 12.48,
        "description": "Rapper",
        "birthplace": "New Delhi",
    },
    {
        "name": "Yo Yo Honey Singh",
        "follower_count": 13.69,
        "description": "Rapper",
        "birthplace": "Hoshiarpur, Punjab",
    },
    {
        "name": "Diljit Dosanjh",
        "follower_count": 20.11,
        "description": "Singer and actor",
        "birthplace": "Dosanjh Kalan, Punjab",
    },
    {
        "name": "CarryMinati",
        "follower_count": 40.97,
        "description": "YouTuber",
        "birthplace": "Faridabad, Haryana",
    },
    {
        "name": "Ashish Chanchlani",
        "follower_count": 16.37,
        "description": "YouTuber",
        "birthplace": "Ulhasnagar, Maharashtra",
    },
    {
        "name": "BB Ki Vines",
        "follower_count": 16.04,
        "description": "YouTuber",
        "birthplace": "Delhi",
    },
    {
        "name": "Technical Guruji",
        "follower_count": 6.82,
        "description": "Tech YouTuber",
        "birthplace": "Ajmer, Rajasthan",
    },
    {
        "name": "Narendra Modi",
        "follower_count": 95.58,
        "description": "Prime Minister of India",
        "birthplace": "Vadnagar, Gujarat",
    },
    {
        "name": "Rahul Gandhi",
        "follower_count": 25.17,
        "description": "Politician",
        "birthplace": "New Delhi",
    },
    {
        "name": "Amit Shah",
        "follower_count": 30.44,
        "description": "Politician",
        "birthplace": "Mumbai, Maharashtra",
    },
    {
        "name": "Arvind Kejriwal",
        "follower_count": 10.63,
        "description": "Politician",
        "birthplace": "Siwani, Haryana",
    },
    {
        "name": "Vicky Kaushal",
        "follower_count": 20.88,
        "description": "Actor",
        "birthplace": "Mumbai, Maharashtra",
    },
    {
        "name": "Rajkummar Rao",
        "follower_count": 9.52,
        "description": "Actor",
        "birthplace": "Gurgaon, Haryana",
    },
    {
        "name": "Ayushmann Khurrana",
        "follower_count": 25.63,
        "description": "Actor and singer",
        "birthplace": "Chandigarh",
    },
    {
        "name": "Sidharth Malhotra",
        "follower_count": 30.71,
        "description": "Actor",
        "birthplace": "Delhi",
    },
    {
        "name": "Varun Dhawan",
        "follower_count": 45.91,
        "description": "Actor",
        "birthplace": "Mumbai, Maharashtra",
    },
    {
        "name": "Tiger Shroff",
        "follower_count": 40.61,
        "description": "Actor",
        "birthplace": "Mumbai, Maharashtra",
    },
    {
        "name": "John Abraham",
        "follower_count": 12.91,
        "description": "Actor",
        "birthplace": "Mumbai, Maharashtra",
    },
    {
        "name": "Manoj Bajpayee",
        "follower_count": 3.74,
        "description": "Actor",
        "birthplace": "Belwa, Bihar",
    },
    {
        "name": "Pankaj Tripathi",
        "follower_count": 6.19,
        "description": "Actor",
        "birthplace": "Belsand, Bihar",
    },
    {
        "name": "Nawazuddin Siddiqui",
        "follower_count": 8.47,
        "description": "Actor",
        "birthplace": "Budhana, Uttar Pradesh",
    },
    {
        "name": "Taapsee Pannu",
        "follower_count": 25.08,
        "description": "Actress",
        "birthplace": "New Delhi",
    },
    {
        "name": "Bhumi Pednekar",
        "follower_count": 15.67,
        "description": "Actress",
        "birthplace": "Mumbai, Maharashtra",
    },
    {
        "name": "Yami Gautam",
        "follower_count": 20.34,
        "description": "Actress",
        "birthplace": "Bilaspur, Himachal Pradesh",
    },
    {
        "name": "Disha Patani",
        "follower_count": 60.42,
        "description": "Actress",
        "birthplace": "Bareilly, Uttar Pradesh",
    },
    {
        "name": "Nora Fatehi",
        "follower_count": 45.67,
        "description": "Dancer and actress",
        "birthplace": "Toronto, Canada",
    },
    {
        "name": "Jacqueline Fernandez",
        "follower_count": 70.53,
        "description": "Actress",
        "birthplace": "Manama, Bahrain",
    },
    {
        "name": "Sonam Kapoor",
        "follower_count": 35.21,
        "description": "Actress",
        "birthplace": "Mumbai, Maharashtra",
    },
    {
        "name": "Ananya Panday",
        "follower_count": 25.41,
        "description": "Actress",
        "birthplace": "Mumbai, Maharashtra",
    },
    {
        "name": "Janhvi Kapoor",
        "follower_count": 25.79,
        "description": "Actress",
        "birthplace": "Mumbai, Maharashtra",
    },
    {
        "name": "Sara Ali Khan",
        "follower_count": 45.48,
        "description": "Actress",
        "birthplace": "Mumbai, Maharashtra",
    },
    {
        "name": "Kapil Dev",
        "follower_count": 3.19,
        "description": "Former cricketer",
        "birthplace": "Chandigarh",
    },
    {
        "name": "Sunil Gavaskar",
        "follower_count": 2.44,
        "description": "Former cricketer",
        "birthplace": "Mumbai, Maharashtra",
    },
    {
        "name": "Anil Kumble",
        "follower_count": 6.73,
        "description": "Former cricketer",
        "birthplace": "Bengaluru, Karnataka",
    },
    {
        "name": "Rahul Dravid",
        "follower_count": 7.58,
        "description": "Former cricketer",
        "birthplace": "Indore, Madhya Pradesh",
    },
    {
        "name": "Mohammed Shami",
        "follower_count": 13.38,
        "description": "Cricketer",
        "birthplace": "Amroha, Uttar Pradesh",
    },
    {
        "name": "Irfan Pathan",
        "follower_count": 12.09,
        "description": "Former cricketer",
        "birthplace": "Vadodara, Gujarat",
    },
    {
        "name": "Harbhajan Singh",
        "follower_count": 11.54,
        "description": "Former cricketer",
        "birthplace": "Jalandhar, Punjab",
    },
    {
        "name": "PV Sindhu",
        "follower_count": 4.66,
        "description": "Badminton player",
        "birthplace": "Hyderabad, Telangana",
    },
    {
        "name": "Saina Nehwal",
        "follower_count": 5.81,
        "description": "Badminton player",
        "birthplace": "Hisar, Haryana",
    },
    {
        "name": "Mary Kom",
        "follower_count": 2.91,
        "description": "Boxer",
        "birthplace": "Kangathei, Manipur",
    },
    {
        "name": "Shreya Ghoshal",
        "follower_count": 30.26,
        "description": "Singer",
        "birthplace": "Berhampore, West Bengal",
    },
    {
        "name": "Sonu Nigam",
        "follower_count": 7.12,
        "description": "Singer",
        "birthplace": "Faridabad, Haryana",
    },
    {
        "name": "Kumar Sanu",
        "follower_count": 3.48,
        "description": "Singer",
        "birthplace": "Kolkata, West Bengal",
    },
    {
        "name": "Divine",
        "follower_count": 6.11,
        "description": "Rapper",
        "birthplace": "Mumbai, Maharashtra",
    },
    {
        "name": "Raftaar",
        "follower_count": 8.91,
        "description": "Rapper",
        "birthplace": "Jalandhar, Punjab",
    },
    {
        "name": "Bhuvan Bam",
        "follower_count": 20.62,
        "description": "YouTuber",
        "birthplace": "Delhi",
    },
    {
        "name": "Triggered Insaan",
        "follower_count": 10.19,
        "description": "YouTuber",
        "birthplace": "Delhi",
    },
    {
        "name": "Flying Beast",
        "follower_count": 7.87,
        "description": "YouTuber",
        "birthplace": "Delhi",
    },
    {
        "name": "Prajakta Koli",
        "follower_count": 8.24,
        "description": "YouTuber",
        "birthplace": "Mumbai, Maharashtra",
    },
    {
        "name": "BeerBiceps",
        "follower_count": 4.13,
        "description": "Podcaster and YouTuber",
        "birthplace": "Mumbai, Maharashtra",
    },
]
